import { useEffect, useMemo, useRef, useState } from 'react';
import type { FC } from 'react';
import {
  ArrowDown as ArrowDownIcon,
  ArrowUp as ArrowUpIcon,
  FilePlus as FilePlusIcon,
  List as ListIcon,
  Plus as PlusIcon,
  Trash2 as TrashIcon,
  UploadCloud as UploadIcon,
  UserPlus as UserPlusIcon,
  Users as UsersIcon,
} from 'lucide-react';

import RichTextEditor from '../../RichTextEditor';
import { uploadFile } from '../../../lib/storageProvider';
import { generateSlug } from '../utils';
import type {
  MediaFormData,
  ToolkitAttachment,
  ToolkitAuthor,
  ToolkitHighlight,
  ToolkitRequirement,
  ToolkitTocItem,
  UploadState,
  ValidationErrors,
} from '../types';
import { ArticleEditorSection } from './ArticleEditorSection';

interface ToolkitFieldsSectionProps {
  formData: MediaFormData;
  errors: ValidationErrors;
  editorJson: any;
  editorHtml: string;
  onEditorChange: (json: any, html: string) => void;
  onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  documentUpload: UploadState;
  onDocumentUpload: (file: File | null | undefined) => Promise<void>;
  onDocumentRemove: () => void;
  docFileInputRef: React.RefObject<HTMLInputElement>;
  setToolkitToc: (items: ToolkitTocItem[]) => void;
  setToolkitRequirements: (items: ToolkitRequirement[]) => void;
  setToolkitHighlights: (items: ToolkitHighlight[]) => void;
  setToolkitAttachments: (items: ToolkitAttachment[]) => void;
  setToolkitAuthors: (items: ToolkitAuthor[]) => void;
  setToolkitChangelog: (json: any, html: string) => void;
}

const generateLocalId = () => {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return Math.random().toString(36).slice(2);
};

const extractHeadingsFromHtml = (html: string): ToolkitTocItem[] => {
  if (typeof window === 'undefined') return [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html || '', 'text/html');
  const headings = Array.from(doc.querySelectorAll('h1, h2, h3, h4, h5, h6'));
  return headings.map((heading, index) => {
    const level = Number(heading.tagName.replace('H', ''));
    const title = (heading.textContent || '').trim() || `Section ${index + 1}`;
    const anchor = heading.id || generateSlug(title);
    return {
      id: heading.id || generateLocalId(),
      title,
      level: Number.isNaN(level) ? 2 : level,
      anchor,
    };
  });
};

const parseFileSizeString = (value: string): number | null => {
  if (!value) return null;
  const match = value.trim().match(/^([\d.,]+)\s*(kb|mb|gb|bytes|b)?$/i);
  if (!match) return null;
  const numeric = parseFloat(match[1].replace(',', ''));
  if (!Number.isFinite(numeric)) return null;
  const unit = (match[2] || 'mb').toLowerCase();
  if (unit === 'kb') return Math.round((numeric / 1024) * 100) / 100;
  if (unit === 'gb') return Math.round(numeric * 1024 * 100) / 100;
  if (unit === 'bytes' || unit === 'b') return Math.round((numeric / (1024 * 1024)) * 100) / 100;
  return Math.round(numeric * 100) / 100;
};

const deriveFileTypeFromUrl = (url: string): string => {
  if (!url) return '';
  const sanitized = url.split('?')[0];
  const extension = sanitized.substring(sanitized.lastIndexOf('.') + 1);
  return extension ? extension.toLowerCase() : '';
};

export const ToolkitFieldsSection: FC<ToolkitFieldsSectionProps> = ({
  formData,
  errors,
  editorJson,
  editorHtml,
  onEditorChange,
  onChange,
  documentUpload,
  onDocumentUpload,
  onDocumentRemove,
  docFileInputRef,
  setToolkitToc,
  setToolkitRequirements,
  setToolkitHighlights,
  setToolkitAttachments,
  setToolkitAuthors,
  setToolkitChangelog,
}) => {
  const autoGeneratedTocRef = useRef(false);
  const [attachmentUploadState, setAttachmentUploadState] = useState<Record<string, UploadState>>({});

  const ensureRequirementIds = useMemo(() => formData.toolkitRequirements.some((item) => !item.id), [formData.toolkitRequirements]);
  const ensureHighlightIds = useMemo(() => formData.toolkitHighlights.some((item) => !item.id), [formData.toolkitHighlights]);
  const ensureAttachmentIds = useMemo(() => formData.toolkitAttachments.some((item) => !item.id), [formData.toolkitAttachments]);
  const ensureAuthorIds = useMemo(() => formData.toolkitAuthors.some((item) => !item.id), [formData.toolkitAuthors]);

  useEffect(() => {
    if (!autoGeneratedTocRef.current && (!formData.toolkitToc || formData.toolkitToc.length === 0) && editorHtml) {
      const tocItems = extractHeadingsFromHtml(editorHtml);
      if (tocItems.length) {
        setToolkitToc(tocItems);
        autoGeneratedTocRef.current = true;
      }
    }
  }, [editorHtml, formData.toolkitToc, setToolkitToc]);

  useEffect(() => {
    if (ensureRequirementIds) {
      setToolkitRequirements(
        formData.toolkitRequirements.map((item, index) => ({
          ...item,
          id: item.id || generateLocalId(),
          order: index,
        }))
      );
    }
  }, [ensureRequirementIds, formData.toolkitRequirements, setToolkitRequirements]);

  useEffect(() => {
    if (ensureHighlightIds) {
      setToolkitHighlights(
        formData.toolkitHighlights.map((item, index) => ({
          ...item,
          id: item.id || generateLocalId(),
          allowMarkComplete: item.allowMarkComplete ?? false,
          order: index,
        }))
      );
    }
  }, [ensureHighlightIds, formData.toolkitHighlights, setToolkitHighlights]);

  useEffect(() => {
    if (ensureAttachmentIds) {
      setToolkitAttachments(
        formData.toolkitAttachments.map((item, index) => ({
          ...item,
          id: item.id || generateLocalId(),
          fileSizeMb: typeof item.fileSizeMb === 'number' ? item.fileSizeMb : null,
          order: (item as any).order ?? index,
        }))
      );
    }
  }, [ensureAttachmentIds, formData.toolkitAttachments, setToolkitAttachments]);

  useEffect(() => {
    if (ensureAuthorIds) {
      setToolkitAuthors(
        formData.toolkitAuthors.map((item, index) => ({
          ...item,
          id: item.id || generateLocalId(),
          order: item.order ?? index,
        }))
      );
    }
  }, [ensureAuthorIds, formData.toolkitAuthors, setToolkitAuthors]);

  const handleRegenerateToc = () => {
    const tocItems = extractHeadingsFromHtml(editorHtml);
    setToolkitToc(tocItems);
  };

  const moveTocItem = (id: string, direction: 'up' | 'down') => {
    const index = formData.toolkitToc.findIndex((item) => item.id === id);
    if (index === -1) return;
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= formData.toolkitToc.length) return;
    const next = [...formData.toolkitToc];
    const [removed] = next.splice(index, 1);
    next.splice(targetIndex, 0, removed);
    setToolkitToc(next);
  };

  const handleRequirementChange = (id: string, field: keyof ToolkitRequirement, value: string) => {
    setToolkitRequirements(
      formData.toolkitRequirements.map((item) => (item.id === id ? { ...item, [field]: value } : item))
    );
  };

  const handleRequirementAdd = () => {
    setToolkitRequirements([
      ...formData.toolkitRequirements,
      { id: generateLocalId(), label: '', value: '', order: formData.toolkitRequirements.length },
    ]);
  };

  const handleRequirementRemove = (id: string) => {
    setToolkitRequirements(formData.toolkitRequirements.filter((item) => item.id !== id));
  };

  const moveRequirement = (id: string, direction: 'up' | 'down') => {
    const index = formData.toolkitRequirements.findIndex((item) => item.id === id);
    if (index === -1) return;
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= formData.toolkitRequirements.length) return;
    const next = [...formData.toolkitRequirements];
    const [removed] = next.splice(index, 1);
    next.splice(targetIndex, 0, removed);
    setToolkitRequirements(next.map((item, idx) => ({ ...item, order: idx })));
  };

  const handleHighlightChange = (id: string, field: keyof ToolkitHighlight, value: string | boolean) => {
    setToolkitHighlights(
      formData.toolkitHighlights.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      )
    );
  };

  const handleHighlightAdd = () => {
    setToolkitHighlights([
      ...formData.toolkitHighlights,
      {
        id: generateLocalId(),
        title: '',
        description: '',
        allowMarkComplete: false,
        order: formData.toolkitHighlights.length,
      },
    ]);
  };

  const handleHighlightRemove = (id: string) => {
    setToolkitHighlights(formData.toolkitHighlights.filter((item) => item.id !== id));
  };

  const moveHighlight = (id: string, direction: 'up' | 'down') => {
    const index = formData.toolkitHighlights.findIndex((item) => item.id === id);
    if (index === -1) return;
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= formData.toolkitHighlights.length) return;
    const next = [...formData.toolkitHighlights];
    const [removed] = next.splice(index, 1);
    next.splice(targetIndex, 0, removed);
    setToolkitHighlights(next.map((item, idx) => ({ ...item, order: idx })));
  };

  const handleAttachmentChange = (id: string, field: keyof ToolkitAttachment, value: string) => {
    setToolkitAttachments(
      formData.toolkitAttachments.map((item) => {
        if (item.id !== id) return item;
        if (field === 'fileSizeMb') {
          const numeric = parseFileSizeString(value);
          return { ...item, fileSizeMb: numeric };
        }
        return { ...item, [field]: value };
      })
    );
  };

  const handleAttachmentAdd = () => {
    setToolkitAttachments([
      ...formData.toolkitAttachments,
      {
        id: generateLocalId(),
        name: '',
        url: '',
        fileType: '',
        fileSizeMb: null,
        order: formData.toolkitAttachments.length,
      },
    ]);
  };

  const handleAttachmentRemove = (id: string) => {
    setToolkitAttachments(formData.toolkitAttachments.filter((item) => item.id !== id));
    setAttachmentUploadState((prev) => {
      const { [id]: _, ...rest } = prev;
      return rest;
    });
  };

  const handleAttachmentUpload = async (id: string, file: File | null | undefined) => {
    if (!file) return;
    setAttachmentUploadState((prev) => ({
      ...prev,
      [id]: { uploadedUrl: '', uploading: true, error: '', fileName: file.name, fileSizeBytes: file.size, contentType: file.type },
    }));
    try {
      const { publicUrl } = await uploadFile({ file, dir: 'report' });
      const fileType = deriveFileTypeFromUrl(file.name) || file.type;
      const sizeMb = Math.round((file.size / (1024 * 1024)) * 100) / 100;
      setToolkitAttachments(
        formData.toolkitAttachments.map((item) =>
          item.id === id
            ? {
                ...item,
                url: publicUrl,
                fileType,
                fileSizeMb: sizeMb,
                name: item.name || file.name,
              }
            : item
        )
      );
      setAttachmentUploadState((prev) => ({
        ...prev,
        [id]: {
          uploadedUrl: publicUrl,
          uploading: false,
          error: '',
          fileName: file.name,
          fileSizeBytes: file.size,
          contentType: file.type,
        },
      }));
    } catch (error: any) {
      setAttachmentUploadState((prev) => ({
        ...prev,
        [id]: {
          uploadedUrl: '',
          uploading: false,
          error: error?.message || 'Upload failed',
        },
      }));
    }
  };

  const moveAttachment = (id: string, direction: 'up' | 'down') => {
    const index = formData.toolkitAttachments.findIndex((item) => item.id === id);
    if (index === -1) return;
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= formData.toolkitAttachments.length) return;
    const next = [...formData.toolkitAttachments];
    const [removed] = next.splice(index, 1);
    next.splice(targetIndex, 0, removed);
    setToolkitAttachments(next.map((item, idx) => ({ ...item, order: idx })));
  };

  const handleAuthorChange = (id: string, field: keyof ToolkitAuthor, value: string | boolean) => {
    setToolkitAuthors(
      formData.toolkitAuthors.map((author) =>
        author.id === id
          ? {
              ...author,
              [field]: value,
            }
          : author
      )
    );
  };

  const handleAuthorAdd = () => {
    const nextAuthors = [
      ...formData.toolkitAuthors,
      {
        id: generateLocalId(),
        name: '',
        organization: '',
        role: '',
        photoUrl: '',
        bio: '',
        isPrimary: formData.toolkitAuthors.length === 0,
        order: formData.toolkitAuthors.length,
      },
    ];
    if (nextAuthors.filter((author) => author.isPrimary).length === 0 && nextAuthors.length > 0) {
      nextAuthors[0].isPrimary = true;
    }
    setToolkitAuthors(nextAuthors);
  };

  const handleAuthorRemove = (id: string) => {
    const nextAuthors = formData.toolkitAuthors.filter((author) => author.id !== id);
    if (nextAuthors.length > 0 && !nextAuthors.some((author) => author.isPrimary)) {
      nextAuthors[0].isPrimary = true;
    }
    setToolkitAuthors(nextAuthors.map((author, index) => ({ ...author, order: index })));
  };

  const moveAuthor = (id: string, direction: 'up' | 'down') => {
    const index = formData.toolkitAuthors.findIndex((author) => author.id === id);
    if (index === -1) return;
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= formData.toolkitAuthors.length) return;
    const next = [...formData.toolkitAuthors];
    const [removed] = next.splice(index, 1);
    next.splice(targetIndex, 0, removed);
    setToolkitAuthors(next.map((author, idx) => ({ ...author, order: idx })));
  };

  const handlePrimaryAuthorSelect = (id: string) => {
    setToolkitAuthors(
      formData.toolkitAuthors.map((author) => ({
        ...author,
        isPrimary: author.id === id,
      }))
    );
  };

  useEffect(() => {
    if (!formData.toolkitFileType && formData.downloadUrl) {
      const derived = deriveFileTypeFromUrl(formData.downloadUrl);
      if (derived) {
        onChange({
          target: {
            name: 'toolkitFileType',
            value: derived,
          },
        } as any);
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [formData.downloadUrl]);

  return (
    <div className="space-y-8">
      <section className="space-y-6">
        <div className="border border-gray-200 rounded-lg overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
            <div>
              <h3 className="text-base font-semibold text-gray-900 flex items-center gap-2">
                <ListIcon className="w-5 h-5 text-blue-500" />
                Toolkit Body
              </h3>
              <p className="text-sm text-gray-500">Create the rich content and outline it automatically.</p>
            </div>
            <button
              type="button"
              onClick={handleRegenerateToc}
              className="inline-flex items-center gap-1 text-sm text-blue-600 hover:text-blue-700"
            >
              <UploadIcon className="w-4 h-4" />
              Regenerate TOC
            </button>
          </div>
          <div className="p-6 space-y-6">
            <ArticleEditorSection editorJson={editorJson} editorHtml={editorHtml} onChange={onEditorChange} errors={errors} />

            <div>
              <h4 className="text-sm font-medium text-gray-800 mb-2">Table of Contents</h4>
              <p className="text-xs text-gray-500 mb-3">Auto-generated from headings. Edit titles and anchors as needed.</p>
              <div className="space-y-3">
                {formData.toolkitToc.length === 0 && (
                  <div className="rounded-md border border-dashed border-gray-300 p-4 text-center text-sm text-gray-500">
                    No headings detected yet. Add headings to the body or click regenerate after editing.
                  </div>
                )}
                {formData.toolkitToc.map((item) => (
                  <div key={item.id} className="border border-gray-200 rounded-md p-4 space-y-3">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Heading Title</label>
                        <input
                          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                          value={item.title}
                          onChange={(event) =>
                            setToolkitToc(
                              formData.toolkitToc.map((node) =>
                                node.id === item.id ? { ...node, title: event.target.value } : node
                              )
                            )
                          }
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Anchor</label>
                        <input
                          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                          value={item.anchor}
                          onChange={(event) =>
                            setToolkitToc(
                              formData.toolkitToc.map((node) =>
                                node.id === item.id ? { ...node, anchor: generateSlug(event.target.value) } : node
                              )
                            )
                          }
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Level</label>
                        <select
                          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                          value={item.level}
                          onChange={(event) =>
                            setToolkitToc(
                              formData.toolkitToc.map((node) =>
                                node.id === item.id
                                  ? { ...node, level: parseInt(event.target.value, 10) || 2 }
                                  : node
                              )
                            )
                          }
                        >
                          {[1, 2, 3, 4, 5, 6].map((level) => (
                            <option key={level} value={level}>
                              Heading {level}
                            </option>
                          ))}
                        </select>
                      </div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                            onClick={() => moveTocItem(item.id, 'up')}
                          className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800"
                          disabled={formData.toolkitToc[0]?.id === item.id}
                        >
                          <ArrowUpIcon className="w-3 h-3" />
                          Up
                        </button>
                        <button
                          type="button"
                            onClick={() => moveTocItem(item.id, 'down')}
                          className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800"
                          disabled={formData.toolkitToc[formData.toolkitToc.length - 1]?.id === item.id}
                        >
                          <ArrowDownIcon className="w-3 h-3" />
                          Down
                        </button>
                      </div>
                      <button
                        type="button"
                        onClick={() => setToolkitToc(formData.toolkitToc.filter((node) => node.id !== item.id))}
                        className="inline-flex items-center gap-1 text-xs text-red-600 hover:text-red-700"
                      >
                        <TrashIcon className="w-3 h-3" />
                        Remove
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="border border-gray-200 rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-base font-semibold text-gray-900">Requirements & Highlights</h3>
          <p className="text-sm text-gray-500">Document prerequisites and key steps for using this toolkit.</p>
        </div>
        <div className="p-6 space-y-8">
          <div>
            <div className="flex items-center justify-between mb-3">
              <h4 className="text-sm font-medium text-gray-800">Requirements / Prerequisites</h4>
              <button
                type="button"
                onClick={handleRequirementAdd}
                className="inline-flex items-center gap-1 text-xs text-blue-600 hover:text-blue-700"
              >
                <PlusIcon className="w-3 h-3" />
                Add requirement
              </button>
            </div>
            <div className="space-y-3">
              {formData.toolkitRequirements.length === 0 && (
                <p className="text-xs text-gray-500">Add items like “Software: Excel” or “Data: Latest sales report”.</p>
              )}
              {formData.toolkitRequirements.map((requirement, index) => (
                <div key={requirement.id} className="border border-gray-200 rounded-md p-4 space-y-3">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-medium text-gray-600 mb-1">Key</label>
                      <input
                        className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                        value={requirement.label}
                        onChange={(event) => handleRequirementChange(requirement.id, 'label', event.target.value)}
                        placeholder="e.g. Software"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-gray-600 mb-1">Details</label>
                      <input
                        className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                        value={requirement.value}
                        onChange={(event) => handleRequirementChange(requirement.id, 'value', event.target.value)}
                        placeholder="e.g. Excel 2019 or newer"
                      />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => moveRequirement(requirement.id, 'up')}
                        disabled={index === 0}
                        className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                      >
                        <ArrowUpIcon className="w-3 h-3" />
                        Up
                      </button>
                      <button
                        type="button"
                        onClick={() => moveRequirement(requirement.id, 'down')}
                        disabled={index === formData.toolkitRequirements.length - 1}
                        className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                      >
                        <ArrowDownIcon className="w-3 h-3" />
                        Down
                      </button>
                    </div>
                    <button
                      type="button"
                      onClick={() => handleRequirementRemove(requirement.id)}
                      className="inline-flex items-center gap-1 text-xs text-red-600 hover:text-red-700"
                    >
                      <TrashIcon className="w-3 h-3" />
                      Remove
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between mb-3">
              <h4 className="text-sm font-medium text-gray-800">Key Highlights / Checklist / Steps</h4>
              <button
                type="button"
                onClick={handleHighlightAdd}
                className="inline-flex items-center gap-1 text-xs text-blue-600 hover:text-blue-700"
              >
                <PlusIcon className="w-3 h-3" />
                Add highlight
              </button>
            </div>
            <div className="space-y-3">
              {formData.toolkitHighlights.length === 0 && (
                <p className="text-xs text-gray-500">Capture the essential steps or takeaways the reader should follow.</p>
              )}
              {formData.toolkitHighlights.map((highlight, index) => (
                <div key={highlight.id} className="border border-gray-200 rounded-md p-4 space-y-3">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-medium text-gray-600 mb-1">Title</label>
                      <input
                        className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                        value={highlight.title}
                        onChange={(event) => handleHighlightChange(highlight.id, 'title', event.target.value)}
                        placeholder="e.g. Prepare your data"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-gray-600 mb-1">Description</label>
                      <input
                        className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                        value={highlight.description}
                        onChange={(event) => handleHighlightChange(highlight.id, 'description', event.target.value)}
                        placeholder="Short explanation"
                      />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <label className="inline-flex items-center gap-2 text-xs text-gray-600">
                      <input
                        type="checkbox"
                        checked={highlight.allowMarkComplete}
                        onChange={(event) => handleHighlightChange(highlight.id, 'allowMarkComplete', event.target.checked)}
                      />
                      Allow mark-complete toggle in UI
                    </label>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => moveHighlight(highlight.id, 'up')}
                        disabled={index === 0}
                        className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                      >
                        <ArrowUpIcon className="w-3 h-3" />
                        Up
                      </button>
                      <button
                        type="button"
                        onClick={() => moveHighlight(highlight.id, 'down')}
                        disabled={index === formData.toolkitHighlights.length - 1}
                        className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                      >
                        <ArrowDownIcon className="w-3 h-3" />
                        Down
                      </button>
                      <button
                        type="button"
                        onClick={() => handleHighlightRemove(highlight.id)}
                        className="inline-flex items-center gap-1 text-xs text-red-600 hover:text-red-700"
                      >
                        <TrashIcon className="w-3 h-3" />
                        Remove
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="border border-gray-200 rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-base font-semibold text-gray-900">Version & Release</h3>
          <p className="text-sm text-gray-500">Capture versioning details and release notes for the toolkit.</p>
        </div>
        <div className="p-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700">Version</label>
              <input
                name="toolkitVersion"
                value={formData.toolkitVersion}
                onChange={onChange}
                placeholder="e.g. v1.0.1"
                className="mt-1 block w-full border border-gray-300 rounded-md py-2 px-3 shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Release Date</label>
              <input
                type="date"
                name="toolkitReleaseDate"
                value={formData.toolkitReleaseDate}
                onChange={onChange}
                className="mt-1 block w-full border border-gray-300 rounded-md py-2 px-3 shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Changelog (optional)</label>
            <div className="mt-1 border border-gray-300 rounded-md">
              <RichTextEditor
                valueJson={formData.toolkitChangelogJson}
                valueHtml={formData.toolkitChangelogHtml}
                onChange={setToolkitChangelog}
                placeholder="Detail changes introduced in this release..."
              />
            </div>
          </div>
        </div>
      </section>

      <section className="border border-gray-200 rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-base font-semibold text-gray-900">Document & Attachments</h3>
          <p className="text-sm text-gray-500">Upload the main toolkit document and any supporting resources.</p>
        </div>
        <div className="p-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-gray-700">
                Document URL <span className="text-red-500">*</span>
              </label>
              <input
                id="downloadUrl"
                name="downloadUrl"
                value={formData.downloadUrl || documentUpload.uploadedUrl}
                onChange={onChange}
                disabled={!!documentUpload.uploadedUrl}
                placeholder="https://..."
                className={`mt-1 block w-full border rounded-md py-2 px-3 ${errors.downloadUrl ? 'border-red-500' : 'border-gray-300'
                  } ${documentUpload.uploadedUrl ? 'bg-gray-50 cursor-not-allowed' : ''}`}
              />
              {errors.downloadUrl && !documentUpload.uploadedUrl && (
                <p className="mt-1 text-xs text-red-600">{errors.downloadUrl}</p>
              )}
              <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-gray-500">
                <div className="flex items-center gap-2">
                  <input
                    ref={docFileInputRef}
                    type="file"
                    onChange={async (event) => {
                      const file = event.target.files?.[0] || null;
                      await onDocumentUpload(file);
                    }}
                  />
                  {documentUpload.uploading && <span>Uploading…</span>}
                  {documentUpload.uploadedUrl && (
                    <span className="text-green-600">Uploaded</span>
                  )}
                </div>
                {documentUpload.uploadedUrl && (
                  <button
                    type="button"
                    className="text-red-600 hover:text-red-700"
                    onClick={onDocumentRemove}
                  >
                    Remove upload
                  </button>
                )}
              </div>
              {documentUpload.uploadedUrl && (
                <div className="mt-2 bg-green-50 border border-green-200 rounded px-2 py-1 text-xs text-green-700 truncate">
                  {documentUpload.uploadedUrl}
                </div>
              )}
              {documentUpload.error && <p className="mt-1 text-xs text-red-600">{documentUpload.error}</p>}
            </div>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  File Type <span className="text-red-500">*</span>
                </label>
                <input
                  id="toolkitFileType"
                  name="toolkitFileType"
                  value={formData.toolkitFileType}
                  onChange={onChange}
                  placeholder="e.g. pdf"
                  className={`mt-1 block w-full border rounded-md py-2 px-3 ${errors.toolkitFileType ? 'border-red-500' : 'border-gray-300'
                    }`}
                />
                {errors.toolkitFileType && <p className="mt-1 text-xs text-red-600">{errors.toolkitFileType}</p>}
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">File Size</label>
                <input
                  name="fileSize"
                  value={formData.fileSize}
                  onChange={onChange}
                  placeholder="e.g. 2 MB"
                  className="mt-1 block w-full border border-gray-300 rounded-md py-2 px-3"
                />
              </div>
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between mb-3">
              <h4 className="text-sm font-medium text-gray-800">Attachments</h4>
              <button
                type="button"
                onClick={handleAttachmentAdd}
                className="inline-flex items-center gap-1 text-xs text-blue-600 hover:text-blue-700"
              >
                <FilePlusIcon className="w-3 h-3" />
                Add attachment
              </button>
            </div>
            <div className="space-y-3">
              {formData.toolkitAttachments.length === 0 && (
                <p className="text-xs text-gray-500">Attach templates, spreadsheets, sample datasets, or supplementary resources.</p>
              )}
              {formData.toolkitAttachments.map((attachment, index) => {
                const uploadState = attachmentUploadState[attachment.id];
                return (
                  <div key={attachment.id} className="border border-gray-200 rounded-md p-4 space-y-3">
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Name</label>
                        <input
                          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                          value={attachment.name}
                          onChange={(event) => handleAttachmentChange(attachment.id, 'name', event.target.value)}
                          placeholder="Attachment name"
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">URL</label>
                        <input
                          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                          value={attachment.url}
                          onChange={(event) => handleAttachmentChange(attachment.id, 'url', event.target.value)}
                          placeholder="https://..."
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">File Type</label>
                        <input
                          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                          value={attachment.fileType}
                          onChange={(event) => handleAttachmentChange(attachment.id, 'fileType', event.target.value)}
                          placeholder="pdf"
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">File Size (MB)</label>
                        <input
                          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                          value={attachment.fileSizeMb ?? ''}
                          onChange={(event) => handleAttachmentChange(attachment.id, 'fileSizeMb', event.target.value)}
                          placeholder="1.2"
                        />
                      </div>
                    </div>
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <label className="text-xs text-gray-500">
                          <input
                            type="file"
                            className="hidden"
                            onChange={async (event) => {
                              const file = event.target.files?.[0] || null;
                              await handleAttachmentUpload(attachment.id, file);
                            }}
                          />
                        </label>
                        <label className="inline-flex items-center gap-2 text-xs text-blue-600 cursor-pointer">
                          <input
                            type="file"
                            className="hidden"
                            onChange={async (event) => {
                              const file = event.target.files?.[0] || null;
                              await handleAttachmentUpload(attachment.id, file);
                            }}
                          />
                          <UploadIcon className="w-3 h-3" />
                          Upload file
                        </label>
                        {uploadState?.uploading && <span className="text-xs text-gray-500">Uploading…</span>}
                        {uploadState?.uploadedUrl && (
                          <span className="text-xs text-green-600">Uploaded</span>
                        )}
                        {uploadState?.error && (
                          <span className="text-xs text-red-600">{uploadState.error}</span>
                        )}
                      </div>
                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => moveAttachment(attachment.id, 'up')}
                          disabled={index === 0}
                          className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                        >
                          <ArrowUpIcon className="w-3 h-3" />
                          Up
                        </button>
                        <button
                          type="button"
                          onClick={() => moveAttachment(attachment.id, 'down')}
                          disabled={index === formData.toolkitAttachments.length - 1}
                          className="inline-flex items-center gap-1 text-xs text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                        >
                          <ArrowDownIcon className="w-3 h-3" />
                          Down
                        </button>
                        <button
                          type="button"
                          onClick={() => handleAttachmentRemove(attachment.id)}
                          className="inline-flex items-center gap-1 text-xs text-red-600 hover:text-red-700"
                        >
                          <TrashIcon className="w-3 h-3" />
                          Remove
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      <section className="border border-gray-200 rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
          <div>
            <h3 className="text-base font-semibold text-gray-900 flex items-center gap-2">
              <UsersIcon className="w-5 h-5 text-blue-500" />
              Authors & Contributors
            </h3>
            <p className="text-sm text-gray-500">Manage multiple authors, set a primary profile, and control display order.</p>
          </div>
          <button
            type="button"
            onClick={handleAuthorAdd}
            className="inline-flex items-center gap-1 text-xs text-blue-600 hover:text-blue-700"
          >
            <UserPlusIcon className="w-3 h-3" />
            Add author
          </button>
        </div>
        <div className="p-6 space-y-4">
          {formData.toolkitAuthors.length === 0 && (
            <p className="text-xs text-gray-500">
              Start by adding at least one author. The primary author syncs with the basic author fields.
            </p>
          )}
          {formData.toolkitAuthors.map((author, index) => (
            <div key={author.id} className="border border-gray-200 rounded-md p-4 space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="primaryAuthor"
                    checked={author.isPrimary}
                    onChange={() => handlePrimaryAuthorSelect(author.id!)}
                  />
                  <span className="text-xs text-gray-600">
                    {author.isPrimary ? 'Primary author' : 'Set as primary'}
                  </span>
                </div>
                <div className="flex items-center gap-2 text-xs">
                  <button
                    type="button"
                    onClick={() => moveAuthor(author.id!, 'up')}
                    disabled={index === 0}
                    className="inline-flex items-center gap-1 text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                  >
                    <ArrowUpIcon className="w-3 h-3" />
                    Up
                  </button>
                  <button
                    type="button"
                    onClick={() => moveAuthor(author.id!, 'down')}
                    disabled={index === formData.toolkitAuthors.length - 1}
                    className="inline-flex items-center gap-1 text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed"
                  >
                    <ArrowDownIcon className="w-3 h-3" />
                    Down
                  </button>
                  <button
                    type="button"
                    onClick={() => handleAuthorRemove(author.id!)}
                    className="inline-flex items-center gap-1 text-red-600 hover:text-red-700"
                  >
                    <TrashIcon className="w-3 h-3" />
                    Remove
                  </button>
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Name</label>
                  <input
                    className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                    value={author.name}
                    onChange={(event) => handleAuthorChange(author.id!, 'name', event.target.value)}
                    placeholder="Author full name"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Organization</label>
                  <input
                    className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                    value={author.organization || ''}
                    onChange={(event) => handleAuthorChange(author.id!, 'organization', event.target.value)}
                    placeholder="Organization"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Role / Title</label>
                  <input
                    className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                    value={author.role || ''}
                    onChange={(event) => handleAuthorChange(author.id!, 'role', event.target.value)}
                    placeholder="Role or title"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Photo URL</label>
                  <input
                    className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                    value={author.photoUrl || ''}
                    onChange={(event) => handleAuthorChange(author.id!, 'photoUrl', event.target.value)}
                    placeholder="https://..."
                  />
                </div>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Bio</label>
                <textarea
                  className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                  rows={3}
                  value={author.bio || ''}
                  onChange={(event) => handleAuthorChange(author.id!, 'bio', event.target.value)}
                  placeholder="Short biography"
                />
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default ToolkitFieldsSection;


