// User data
export const userData = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2023-06-15',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    role: 'Editor',
    status: 'Active',
    lastLogin: '2023-06-14',
  },
  {
    id: '3',
    name: 'Michael Brown',
    email: 'm.brown@example.com',
    role: 'Viewer',
    status: 'Inactive',
    lastLogin: '2023-05-20',
  },
  {
    id: '4',
    name: 'Jessica Lee',
    email: 'jessica@example.com',
    role: 'Editor',
    status: 'Active',
    lastLogin: '2023-06-13',
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'd.wilson@example.com',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2023-06-15',
  },
]

// Columns for user table
export const userColumns = [
  { key: 'name', label: 'Name', primary: true },
  { key: 'email', label: 'Email' },
  { key: 'role', label: 'Role' },
  { key: 'status', label: 'Status' },
  { key: 'lastLogin', label: 'Last Login' },
]

// Content data
export const contentData = [
  {
    id: '1',
    title: 'Homepage Banner',
    type: 'Banner',
    status: 'Published',
    author: 'John Smith',
    lastModified: '2023-06-14',
  },
  {
    id: '2',
    title: 'About Us Page',
    type: 'Page',
    status: 'Draft',
    author: 'Sarah Johnson',
    lastModified: '2023-06-13',
  },
  {
    id: '3',
    title: 'Summer Promotion',
    type: 'Campaign',
    status: 'Published',
    author: 'Michael Brown',
    lastModified: '2023-06-10',
  },
  {
    id: '4',
    title: 'Product Catalog',
    type: 'Page',
    status: 'Published',
    author: 'Jessica Lee',
    lastModified: '2023-06-08',
  },
  {
    id: '5',
    title: 'Newsletter Template',
    type: 'Email',
    status: 'Draft',
    author: 'David Wilson',
    lastModified: '2023-06-12',
  },
]

// Columns for content table
export const contentColumns = [
  { key: 'title', label: 'Title', primary: true },
  { key: 'type', label: 'Type' },
  { key: 'status', label: 'Status' },
  { key: 'author', label: 'Author' },
  { key: 'lastModified', label: 'Last Modified' },
]

// Analytics data
export const analyticsData = [
  {
    id: '1',
    metric: 'Page Views',
    value: '125,430',
    change: '+5.2%',
    period: 'Last 30 days',
  },
  {
    id: '2',
    metric: 'Unique Visitors',
    value: '45,872',
    change: '+3.8%',
    period: 'Last 30 days',
  },
  {
    id: '3',
    metric: 'Conversion Rate',
    value: '3.2%',
    change: '+0.5%',
    period: 'Last 30 days',
  },
  {
    id: '4',
    metric: 'Avg. Session Duration',
    value: '2m 45s',
    change: '-0.3%',
    period: 'Last 30 days',
  },
  {
    id: '5',
    metric: 'Bounce Rate',
    value: '42.1%',
    change: '-1.5%',
    period: 'Last 30 days',
  },
]

// Columns for analytics table
export const analyticsColumns = [
  { key: 'metric', label: 'Metric', primary: true },
  { key: 'value', label: 'Value' },
  { key: 'change', label: 'Change' },
  { key: 'period', label: 'Period' },
]

// Settings data
export const settingsData = [
  {
    id: '1',
    setting: 'Email Notifications',
    value: 'Enabled',
    lastUpdated: '2023-06-10',
    updatedBy: 'John Smith',
  },
  {
    id: '2',
    setting: 'Two-Factor Authentication',
    value: 'Required',
    lastUpdated: '2023-06-05',
    updatedBy: 'David Wilson',
  },
  {
    id: '3',
    setting: 'API Access',
    value: 'Limited',
    lastUpdated: '2023-05-28',
    updatedBy: 'Sarah Johnson',
  },
  {
    id: '4',
    setting: 'Data Retention',
    value: '90 days',
    lastUpdated: '2023-06-01',
    updatedBy: 'Michael Brown',
  },
  {
    id: '5',
    setting: 'User Registration',
    value: 'Approval Required',
    lastUpdated: '2023-06-12',
    updatedBy: 'Jessica Lee',
  },
]

// Columns for settings table
export const settingsColumns = [
  { key: 'setting', label: 'Setting', primary: true },
  { key: 'value', label: 'Value' },
  { key: 'lastUpdated', label: 'Last Updated' },
  { key: 'updatedBy', label: 'Updated By' },
]

// Tab sections data
export const dashboardTabs = [
  {
    id: '1',
    title: 'Overview',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '2',
    title: 'Recent Activity',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '3',
    title: 'Notifications',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
]

export const usersTabs = [
  {
    id: '1',
    title: 'All Users',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '2',
    title: 'Admins',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '3',
    title: 'Pending Approvals',
    completion: 75,
    mandatoryCompletion: { percentage: 50 },
  },
]

export const contentTabs = [
  {
    id: '1',
    title: 'All Content',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '2',
    title: 'Published',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '3',
    title: 'Drafts',
    completion: 85,
    mandatoryCompletion: { percentage: 70 },
  },
  {
    id: '4',
    title: 'Archived',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
]

export const analyticsTabs = [
  {
    id: '1',
    title: 'Traffic Overview',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '2',
    title: 'User Engagement',
    completion: 90,
    mandatoryCompletion: { percentage: 80 },
  },
  {
    id: '3',
    title: 'Conversion Metrics',
    completion: 85,
    mandatoryCompletion: { percentage: 70 },
  },
]

export const settingsTabs = [
  {
    id: '1',
    title: 'General',
    completion: 100,
    mandatoryCompletion: { percentage: 100 },
  },
  {
    id: '2',
    title: 'Security',
    completion: 90,
    mandatoryCompletion: { percentage: 85 },
  },
  {
    id: '3',
    title: 'Integrations',
    completion: 70,
    mandatoryCompletion: { percentage: 50 },
  },
  {
    id: '4',
    title: 'Notifications',
    completion: 80,
    mandatoryCompletion: { percentage: 75 },
  },
]

// Company data for sidebar
export const companies = [
  {
    id: '1',
    name: 'Main Organization',
    role: 'Admin',
    isActive: true,
    badge: 'Primary',
  },
  { id: '2', name: 'Partner Company', role: 'Editor', badge: 'Secondary' },
  { id: '3', name: 'Client Organization', role: 'Viewer', badge: '' },
]

// Mock data for businesses in Abu Dhabi
export const mockBusinesses = [
  {
    id: '1',
    name: 'Abu Dhabi National Oil Company',
    type: 'Government',
    industry: 'Energy & Utilities',
    size: 'Enterprise',
    status: 'Active',
    foundedYear: '1971',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/ADNOC_logo.svg/1200px-ADNOC_logo.svg.png',
    description:
      "One of the world's leading energy producers, specializing in exploration, production, storage, refining, and distribution of oil and gas.",
    address: {
      street: 'ADNOC Headquarters, Corniche Road',
      city: 'Abu Dhabi',
      region: 'Abu Dhabi',
      postalCode: '898',
      country: 'United Arab Emirates',
      coordinates: { lat: 24.4667, lng: 54.3667 },
    },
    phone: '+971-2-707-0000',
    email: 'contact@adnoc.ae',
    website: 'https://www.adnoc.ae',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/adnoc/',
      twitter: 'https://twitter.com/adnocgroup',
      facebook: 'https://www.facebook.com/ADNOC/',
      instagram: 'https://www.instagram.com/adnocgroup/',
    },
    keyPeople: [
      { name: 'Dr. Sultan Al Jaber', role: 'Group CEO' },
      { name: 'Abdulmunim Saif Al Kindy', role: 'Executive Director' },
    ],
    employees: '50,000+',
    products: [
      {
        name: 'Crude Oil Production',
        description:
          'Exploration and production of crude oil from various fields.',
        category: 'Energy',
      },
      {
        name: 'Natural Gas Processing',
        description:
          'Processing and distribution of natural gas for domestic and international markets.',
        category: 'Energy',
      },
      {
        name: 'Petrochemicals',
        description: 'Manufacturing of various petrochemical products.',
        category: 'Chemicals',
      },
    ],
    certifications: [
      'ISO 14001 Environmental Management',
      'ISO 9001 Quality Management',
      'OHSAS 18001 Occupational Health and Safety',
    ],
    financials: {
      revenue: '$62.5 billion (2021)',
      revenueGrowth: '15.2',
      marketShare: '12% (Regional)',
      profitMargin: '18.7%',
      investments: [
        {
          round: 'Expansion Project',
          amount: '$20.7 billion',
          date: '2020-2025',
          details:
            'Investment in expanding refining and petrochemical operations',
        },
      ],
      reports: [
        { title: 'Annual Sustainability Report', year: '2022' },
        { title: 'Financial Performance Summary', year: '2021' },
      ],
    },
    licenseInfo: {
      number: 'GOV-EN-1971-001',
      issuedDate: '1971-01-01',
      expiryDate: 'Perpetual',
      authority: 'Government of Abu Dhabi',
    },
  },
  {
    id: '2',
    name: 'Etihad Airways',
    type: 'Government',
    industry: 'Aviation',
    size: 'Large',
    status: 'Active',
    foundedYear: '2003',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Etihad_Airways_logo_2022.svg/2560px-Etihad_Airways_logo_2022.svg.png',
    description:
      'The second-largest airline of the UAE. The airline operates more than 1,000 flights per week to over 120 passenger and cargo destinations.',
    address: {
      street: 'New Airport Road',
      city: 'Abu Dhabi',
      region: 'Abu Dhabi',
      postalCode: '35566',
      country: 'United Arab Emirates',
      coordinates: { lat: 24.433, lng: 54.6511 },
    },
    phone: '+971-2-599-0000',
    email: 'info@etihad.ae',
    website: 'https://www.etihad.com',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/etihad-airways/',
      twitter: 'https://twitter.com/etihad',
      facebook: 'https://www.facebook.com/etihad/',
      instagram: 'https://www.instagram.com/etihad/',
    },
    keyPeople: [{ name: 'Antonoaldo Neves', role: 'CEO' }],
    employees: '20,000+',
    products: [
      {
        name: 'Passenger Air Transport',
        description:
          'Scheduled passenger flights to international destinations.',
        category: 'Aviation',
      },
      {
        name: 'Cargo Services',
        description: 'Air freight and logistics services worldwide.',
        category: 'Logistics',
      },
      {
        name: 'Etihad Holidays',
        description: 'Vacation packages and travel services.',
        category: 'Tourism',
      },
    ],
    certifications: [
      'IATA Operational Safety Audit (IOSA)',
      'ISO 14001:2015 Environmental Management',
      'ISO 9001:2015 Quality Management',
    ],
    financials: {
      revenue: '$4.9 billion (2021)',
      revenueGrowth: '29.7',
      marketShare: '8% (Global)',
      profitMargin: '5.6%',
    },
    licenseInfo: {
      number: 'GCAA-AIR-2003-001',
      issuedDate: '2003-07-14',
      expiryDate: '2028-07-14',
      authority: 'General Civil Aviation Authority',
    },
  },
  // ... remaining businesses would continue here but truncated for brevity
]

// Growth Areas mock data
export const mockGrowthAreas = [
  {
    id: '1',
    name: 'Renewable Energy',
    type: 'Strategic',
    category: 'Energy',
    status: 'Growing',
    growthRate: 12.5,
    submittedOn: '2023-05-15T10:30:00Z',
    icon: { name: 'LightbulbIcon' },
    iconColor: 'text-green-600',
    iconBgColor: 'bg-green-100',
    description:
      'Development of renewable energy sources including solar, wind, and hydrogen technologies.',
    keyStatistics: [
      {
        label: 'Market Size',
        value: '$15.2 Billion',
        change: 12.5,
      },
      {
        label: 'Employment',
        value: '35,000+',
        change: 8.7,
      },
      {
        label: 'Investment (2023)',
        value: '$3.8 Billion',
        change: 15.0,
      },
      {
        label: 'Contribution to GDP',
        value: '4.2%',
        change: 3.8,
      },
    ],
    growthProjection: {
      rate: 15.8,
      period: 'CAGR (2023-2028)',
      description:
        'Growth driven by increased government investment, favorable policies, and global shift toward sustainable energy solutions.',
    },
    associatedZones: [],
    keyPlayers: [],
    associatedBusinesses: [],
    economicImpact: [],
    employment: [],
    marketTrends: [],
    comparativeAnalysis: {
      description: '',
      regionalComparison: [],
      advantages: [],
    },
    industryBreakdown: [],
    investmentOpportunities: [],
    supportPrograms: [],
    contactInformation: {},
  },
  // ... remaining growth areas truncated for brevity
]

// Mock data for services
export const mockServices = [
  {
    id: '1',
    title: 'Small Business Loan Program',
    type: 'Financial',
    partner: 'Capital Finance Group',
    category: 'Funding',
    processingTime: '10 Business Days',
    status: 'Pending',
    applicants: 0,
    feedback: {
      rating: 0,
      count: 0,
    },
    submittedOn: '2023-06-14 09:30:45',
    description:
      'Low-interest loans for small businesses with flexible repayment terms. Designed to support business growth and operational expenses.',
    eligibility: [
      'Business must be operating for at least 1 year',
      'Annual revenue between $50,000 and $2 million',
      'Credit score of 650 or higher',
    ],
    applicationRequirements: [
      'Business financial statements',
      'Tax returns for last 2 years',
      'Business plan',
    ],
    fee: '$250 application fee',
    regulatoryCategory: 'Lending',
    documentsRequired: [
      'Business License',
      'Financial Statements',
      'Tax Returns',
    ],
    partnerInfo: {
      name: 'Capital Finance Group',
      email: 'partner@capitalfinance.example.com',
      tier: 'Gold',
      totalSubmissions: 15,
      approvalRate: 85,
      complianceNotes: 'All licenses verified and current.',
    },
    comments: [
      {
        id: '1',
        author: 'Sarah Johnson',
        role: 'Moderator',
        text: 'Interest rates need to be clearly disclosed in the description.',
        timestamp: '2023-06-14 10:15:22',
      },
      {
        id: '2',
        author: 'David Wilson',
        role: 'Compliance',
        text: 'Need to verify lending license is up-to-date before approval.',
        timestamp: '2023-06-14 11:30:45',
      },
    ],
    activityLog: [],
  },
  // ... remaining services truncated for brevity
]

// Taxonomy mock data - Vendure-aligned structure
export const mockTaxonomies = [
  {
    id: '1',
    name: 'Business Stage',
    type: 'Collection',
    scope: 'Marketplace',
    slug: 'business-stage',
    description:
      'Hierarchical categories representing different stages of business development and maturity.',
    status: 'Active',
    valuesCount: 5,
    lastUpdated: '2024-01-15T10:30:00Z',
    createdBy: 'Admin User',
    parentId: null,
    displayOrder: 1,
    children: [
      {
        id: '1-1',
        name: 'Early Stage',
        parentId: '1',
        displayOrder: 1,
        status: 'Active',
        children: [
          {
            id: '1-1-1',
            name: 'Idea',
            parentId: '1-1',
            displayOrder: 1,
            status: 'Active',
            usageCount: 45,
          },
          {
            id: '1-1-2',
            name: 'Startup',
            parentId: '1-1',
            displayOrder: 2,
            status: 'Active',
            usageCount: 142,
          },
        ],
      },
      {
        id: '1-2',
        name: 'Growth Stage',
        parentId: '1',
        displayOrder: 2,
        status: 'Active',
        children: [
          {
            id: '1-2-1',
            name: 'Growth',
            parentId: '1-2',
            displayOrder: 1,
            status: 'Active',
            usageCount: 98,
          },
          {
            id: '1-2-2',
            name: 'Expansion',
            parentId: '1-2',
            displayOrder: 2,
            status: 'Active',
            usageCount: 67,
          },
        ],
      },
      {
        id: '1-3',
        name: 'Mature',
        parentId: '1',
        displayOrder: 3,
        status: 'Active',
        usageCount: 45,
      },
    ],
  },
  {
    id: '2',
    name: 'Service Category',
    type: 'Collection',
    scope: 'Marketplace',
    slug: 'service-category',
    description:
      'Main hierarchical categories for classifying services offered on the platform.',
    status: 'Active',
    valuesCount: 8,
    lastUpdated: '2024-01-20T14:15:00Z',
    createdBy: 'Admin User',
    parentId: null,
    displayOrder: 2,
    children: [
      {
        id: '2-1',
        name: 'Financial Services',
        parentId: '2',
        displayOrder: 1,
        status: 'Active',
        children: [
          {
            id: '2-1-1',
            name: 'Funding',
            parentId: '2-1',
            displayOrder: 1,
            status: 'Active',
            usageCount: 234,
          },
          {
            id: '2-1-2',
            name: 'Investment',
            parentId: '2-1',
            displayOrder: 2,
            status: 'Active',
            usageCount: 87,
          },
        ],
      },
      {
        id: '2-2',
        name: 'Business Support',
        parentId: '2',
        displayOrder: 2,
        status: 'Active',
        children: [
          {
            id: '2-2-1',
            name: 'Advisory',
            parentId: '2-2',
            displayOrder: 1,
            status: 'Active',
            usageCount: 189,
          },
          {
            id: '2-2-2',
            name: 'Training',
            parentId: '2-2',
            displayOrder: 2,
            status: 'Active',
            usageCount: 156,
          },
          {
            id: '2-2-3',
            name: 'Legal',
            parentId: '2-2',
            displayOrder: 3,
            status: 'Active',
            usageCount: 76,
          },
        ],
      },
      {
        id: '2-3',
        name: 'Technology',
        parentId: '2',
        displayOrder: 3,
        status: 'Active',
        usageCount: 54,
      },
    ],
  },
  {
    id: '3',
    name: 'Industry Sector',
    type: 'Facet',
    scope: 'Marketplace',
    slug: 'industry-sector',
    description:
      'Industry sectors for categorizing and filtering businesses and services.',
    status: 'Active',
    valuesCount: 12,
    lastUpdated: '2024-01-18T09:45:00Z',
    createdBy: 'Content Manager',
    values: [
      {
        id: 'v14',
        name: 'Technology',
        code: 'TECH',
        color: '#3B82F6',
        icon: 'CpuIcon',
        displayOrder: 1,
        usageCount: 312,
        status: 'Active',
      },
      {
        id: 'v15',
        name: 'Healthcare',
        code: 'HEALTH',
        color: '#10B981',
        icon: 'HeartIcon',
        displayOrder: 2,
        usageCount: 267,
        status: 'Active',
      },
      {
        id: 'v16',
        name: 'Finance',
        code: 'FINANCE',
        color: '#F59E0B',
        icon: 'DollarSignIcon',
        displayOrder: 3,
        usageCount: 245,
        status: 'Active',
      },
      {
        id: 'v17',
        name: 'Retail',
        code: 'RETAIL',
        color: '#8B5CF6',
        icon: 'ShoppingBagIcon',
        displayOrder: 4,
        usageCount: 198,
        status: 'Active',
      },
      {
        id: 'v18',
        name: 'Manufacturing',
        code: 'MFG',
        color: '#6366F1',
        icon: 'FactoryIcon',
        displayOrder: 5,
        usageCount: 176,
        status: 'Active',
      },
      {
        id: 'v19',
        name: 'Education',
        code: 'EDU',
        color: '#EC4899',
        icon: 'BookOpenIcon',
        displayOrder: 6,
        usageCount: 154,
        status: 'Active',
      },
      {
        id: 'v20',
        name: 'Real Estate',
        code: 'REALESTATE',
        color: '#14B8A6',
        icon: 'HomeIcon',
        displayOrder: 7,
        usageCount: 132,
        status: 'Active',
      },
      {
        id: 'v21',
        name: 'Transportation',
        code: 'TRANSPORT',
        color: '#F97316',
        icon: 'TruckIcon',
        displayOrder: 8,
        usageCount: 98,
        status: 'Active',
      },
      {
        id: 'v22',
        name: 'Hospitality',
        code: 'HOSP',
        color: '#A855F7',
        icon: 'CoffeeIcon',
        displayOrder: 9,
        usageCount: 87,
        status: 'Active',
      },
      {
        id: 'v23',
        name: 'Agriculture',
        code: 'AGRI',
        color: '#84CC16',
        icon: 'LeafIcon',
        displayOrder: 10,
        usageCount: 76,
        status: 'Active',
      },
      {
        id: 'v24',
        name: 'Energy',
        code: 'ENERGY',
        color: '#EAB308',
        icon: 'ZapIcon',
        displayOrder: 11,
        usageCount: 65,
        status: 'Active',
      },
      {
        id: 'v25',
        name: 'Construction',
        code: 'CONST',
        color: '#F43F5E',
        icon: 'HammerIcon',
        displayOrder: 12,
        usageCount: 54,
        status: 'Active',
      },
    ],
  },
  {
    id: '4',
    name: 'Content Type',
    type: 'Collection',
    scope: 'Content',
    slug: 'content-type',
    description: 'Hierarchical types of content published on the platform.',
    status: 'Active',
    valuesCount: 6,
    lastUpdated: '2024-01-22T11:20:00Z',
    createdBy: 'Content Manager',
    parentId: null,
    displayOrder: 1,
    children: [
      {
        id: '4-1',
        name: 'Written Content',
        parentId: '4',
        displayOrder: 1,
        status: 'Active',
        children: [
          {
            id: '4-1-1',
            name: 'Article',
            parentId: '4-1',
            displayOrder: 1,
            status: 'Active',
            usageCount: 456,
          },
          {
            id: '4-1-2',
            name: 'Guide',
            parentId: '4-1',
            displayOrder: 2,
            status: 'Active',
            usageCount: 234,
          },
          {
            id: '4-1-3',
            name: 'Case Study',
            parentId: '4-1',
            displayOrder: 3,
            status: 'Active',
            usageCount: 76,
          },
        ],
      },
      {
        id: '4-2',
        name: 'Media Content',
        parentId: '4',
        displayOrder: 2,
        status: 'Active',
        children: [
          {
            id: '4-2-1',
            name: 'Video',
            parentId: '4-2',
            displayOrder: 1,
            status: 'Active',
            usageCount: 189,
          },
          {
            id: '4-2-2',
            name: 'Podcast',
            parentId: '4-2',
            displayOrder: 2,
            status: 'Active',
            usageCount: 123,
          },
          {
            id: '4-2-3',
            name: 'Infographic',
            parentId: '4-2',
            displayOrder: 3,
            status: 'Active',
            usageCount: 98,
          },
        ],
      },
    ],
  },
  {
    id: '5',
    name: 'Content Tags',
    type: 'Tag',
    scope: 'Content',
    slug: 'content-tags',
    description: 'Flexible tags for content organization and discovery.',
    status: 'Active',
    valuesCount: 15,
    lastUpdated: '2024-01-25T16:30:00Z',
    createdBy: 'Content Manager',
    usageCount: 1876,
    tags: [
      {
        id: 't1',
        name: 'Entrepreneurship',
        slug: 'entrepreneurship',
        usageCount: 234,
        status: 'Active',
      },
      {
        id: 't2',
        name: 'Innovation',
        slug: 'innovation',
        usageCount: 198,
        status: 'Active',
      },
      {
        id: 't3',
        name: 'Leadership',
        slug: 'leadership',
        usageCount: 176,
        status: 'Active',
      },
      {
        id: 't4',
        name: 'Strategy',
        slug: 'strategy',
        usageCount: 154,
        status: 'Active',
      },
      {
        id: 't5',
        name: 'Digital Transformation',
        slug: 'digital-transformation',
        usageCount: 132,
        status: 'Active',
      },
      {
        id: 't6',
        name: 'Sustainability',
        slug: 'sustainability',
        usageCount: 121,
        status: 'Active',
      },
      {
        id: 't7',
        name: 'Funding',
        slug: 'funding',
        usageCount: 109,
        status: 'Active',
      },
      {
        id: 't8',
        name: 'Marketing',
        slug: 'marketing',
        usageCount: 98,
        status: 'Active',
      },
      {
        id: 't9',
        name: 'Technology',
        slug: 'technology',
        usageCount: 87,
        status: 'Active',
      },
      {
        id: 't10',
        name: 'Growth',
        slug: 'growth',
        usageCount: 76,
        status: 'Active',
      },
      {
        id: 't11',
        name: 'Networking',
        slug: 'networking',
        usageCount: 65,
        status: 'Active',
      },
      {
        id: 't12',
        name: 'Best Practices',
        slug: 'best-practices',
        usageCount: 54,
        status: 'Active',
      },
      {
        id: 't13',
        name: 'Case Studies',
        slug: 'case-studies',
        usageCount: 43,
        status: 'Active',
      },
      {
        id: 't14',
        name: 'Trends',
        slug: 'trends',
        usageCount: 32,
        status: 'Active',
      },
      {
        id: 't15',
        name: 'Resources',
        slug: 'resources',
        usageCount: 21,
        status: 'Active',
      },
    ],
  },
  {
    id: '6',
    name: 'Pricing Model',
    type: 'Facet',
    scope: 'Marketplace',
    slug: 'pricing-model',
    description: 'Different pricing models for filtering services.',
    status: 'Active',
    valuesCount: 4,
    lastUpdated: '2024-01-19T13:10:00Z',
    createdBy: 'Admin User',
    values: [
      {
        id: 'v47',
        name: 'Free',
        code: 'FREE',
        color: '#10B981',
        icon: 'GiftIcon',
        displayOrder: 1,
        usageCount: 89,
        status: 'Active',
      },
      {
        id: 'v48',
        name: 'One-time Fee',
        code: 'ONETIME',
        color: '#3B82F6',
        icon: 'DollarSignIcon',
        displayOrder: 2,
        usageCount: 156,
        status: 'Active',
      },
      {
        id: 'v49',
        name: 'Subscription',
        code: 'SUBSCRIPTION',
        color: '#8B5CF6',
        icon: 'RepeatIcon',
        displayOrder: 3,
        usageCount: 134,
        status: 'Active',
      },
      {
        id: 'v50',
        name: 'Variable',
        code: 'VARIABLE',
        color: '#F59E0B',
        icon: 'TrendingUpIcon',
        displayOrder: 4,
        usageCount: 98,
        status: 'Active',
      },
    ],
  },
  {
    id: '7',
    name: 'Target Audience',
    type: 'Facet',
    scope: 'Content',
    slug: 'target-audience',
    description: 'Target audience segments for filtering content.',
    status: 'Active',
    valuesCount: 5,
    lastUpdated: '2024-01-21T10:00:00Z',
    createdBy: 'Content Manager',
    values: [
      {
        id: 'v51',
        name: 'Startups',
        code: 'STARTUPS',
        color: '#10B981',
        icon: 'RocketIcon',
        displayOrder: 1,
        usageCount: 267,
        status: 'Active',
      },
      {
        id: 'v52',
        name: 'SMEs',
        code: 'SMES',
        color: '#3B82F6',
        icon: 'BuildingIcon',
        displayOrder: 2,
        usageCount: 234,
        status: 'Active',
      },
      {
        id: 'v53',
        name: 'Enterprises',
        code: 'ENTERPRISE',
        color: '#8B5CF6',
        icon: 'Building2Icon',
        displayOrder: 3,
        usageCount: 189,
        status: 'Active',
      },
      {
        id: 'v54',
        name: 'Investors',
        code: 'INVESTORS',
        color: '#F59E0B',
        icon: 'TrendingUpIcon',
        displayOrder: 4,
        usageCount: 156,
        status: 'Active',
      },
      {
        id: 'v55',
        name: 'General Public',
        code: 'PUBLIC',
        color: '#6366F1',
        icon: 'UsersIcon',
        displayOrder: 5,
        usageCount: 198,
        status: 'Active',
      },
    ],
  },
  {
    id: '8',
    name: 'Legacy Categories',
    type: 'Collection',
    scope: 'Marketplace',
    slug: 'legacy-categories',
    description: 'Deprecated category system from previous platform version.',
    status: 'Archived',
    valuesCount: 3,
    lastUpdated: '2023-12-10T08:30:00Z',
    createdBy: 'System',
    parentId: null,
    displayOrder: 99,
    children: [
      {
        id: '8-1',
        name: 'Old Category 1',
        parentId: '8',
        displayOrder: 1,
        status: 'Archived',
        usageCount: 0,
      },
      {
        id: '8-2',
        name: 'Old Category 2',
        parentId: '8',
        displayOrder: 2,
        status: 'Archived',
        usageCount: 0,
      },
      {
        id: '8-3',
        name: 'Old Category 3',
        parentId: '8',
        displayOrder: 3,
        status: 'Archived',
        usageCount: 0,
      },
    ],
  },
]
